### ISSUE TITLE
Esphome device not serving config.yaml

### ISSUE THREAD

**Issue by LordMike** [TMaYaD/esphome-plus#26]
Hey - I tried this project out to see if I could get something from it :)
I'm a bit stumped though. I've installed it using `pipx` and ran it, but it seems unable to download the current config from my device.

Is there a thing I need to configure on my devices, to expose the current configuration, for the `reconcile` command to work?

```
# /root/.local/bin/esphome-plus reconcile light-41-6_shellyduorgbw.yaml
Reconciling light-41-6_shellyduorgbw.yaml
Error fetching YAML from light-41-6.c.home: 500 Server Error: Internal Server Error for url: http://light-41-6.c.home/config.yaml
Traceback (most recent call last):
  File "/root/.local/bin/esphome-plus", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/root/.local/pipx/venvs/esphome-plus/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/esphome-plus/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/esphome-plus/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/esphome-plus/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/esphome-plus/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/esphome-plus/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/esphome-plus/lib/python3.11/site-packages/esphome_plus/reconcile.py", line 37, in reconcile
    reconcile_file(ctx, config_path, **kwargs)
  File "/root/.local/pipx/venvs/esphome-plus/lib/python3.11/site-packages/esphome_plus/reconcile.py", line 68, in reconcile_file
    current_config = load_config_content_from_device(config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/esphome-plus/lib/python3.11/site-packages/esphome_plus/reconcile.py", line 119, in load_config_content_from_device
    raise e
  File "/root/.local/pipx/venvs/esphome-plus/lib/python3.11/site-packages/esphome_plus/reconcile.py", line 114, in load_config_content_from_device
    response.raise_for_status()  # Check for HTTP errors
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/esphome-plus/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://light-41-6.c.home/config.yaml
```

Mike.

**Comment by TMaYaD** [comment]
Oh wow! I didn't expect anyone to use it. It's no where near production quality.

That being said, this uses the [backup component by dentra](https://github.com/dentra/esphome-components/tree/master/components/backup)

```yaml
external_components:
  - source: github://dentra/esphome-components

backup:
```

Note: Auth is not supported yet.

**Comment by LordMike** [comment]
Ah! I read the code for esphome and couldn’t find anything for the config. An external component makes sense. :)

Mike.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TMaYaD** [comment]
Note: There is a bug dentra/esphome-components#53 with upstream backup component. Use `tmayad/esphome-components` until dentra/esphome-components#54 is merged in.
